//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.group._3_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ddi.reusable._3_1.ReferenceType;


/**
 * Allows for inclusion of a physical data product for reuse by reference.
 * 
 * <p>Java class for PhysicalDataProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysicalDataProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{ddi:physicaldataproduct:3_1}PhysicalDataProduct"/>
 *         &lt;element ref="{ddi:group:3_1}Reference"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalDataProductType", propOrder = {
    "physicalDataProduct",
    "reference"
})
public class PhysicalDataProductType {

    @XmlElement(name = "PhysicalDataProduct", namespace = "ddi:physicaldataproduct:3_1")
    protected ddi.physicaldataproduct._3_1.PhysicalDataProductType physicalDataProduct;
    @XmlElement(name = "Reference")
    protected ReferenceType reference;

    /**
     * Contains a physical data product module.
     * 
     * @return
     *     possible object is
     *     {@link ddi.physicaldataproduct._3_1.PhysicalDataProductType }
     *     
     */
    public ddi.physicaldataproduct._3_1.PhysicalDataProductType getPhysicalDataProduct() {
        return physicalDataProduct;
    }

    /**
     * Sets the value of the physicalDataProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link ddi.physicaldataproduct._3_1.PhysicalDataProductType }
     *     
     */
    public void setPhysicalDataProduct(ddi.physicaldataproduct._3_1.PhysicalDataProductType value) {
        this.physicalDataProduct = value;
    }

    /**
     * References an external physical data product module.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setReference(ReferenceType value) {
        this.reference = value;
    }

}
