//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.group._3_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ddi.reusable._3_1.ReferenceType;


/**
 * Allows for inclusion of a study unit that belongs to the group as a direct child. Subgroups may also contain study units, and individual study units and subgroups may be members of a single group. Study units can be included in any group or subgroup either as in-line documentation/metadata or by reference.
 * 
 * <p>Java class for StudyUnitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudyUnitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{ddi:studyunit:3_1}StudyUnit"/>
 *         &lt;element ref="{ddi:group:3_1}Reference"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudyUnitType", propOrder = {
    "studyUnit",
    "reference"
})
public class StudyUnitType {

    @XmlElement(name = "StudyUnit", namespace = "ddi:studyunit:3_1")
    protected ddi.studyunit._3_1.StudyUnitType studyUnit;
    @XmlElement(name = "Reference")
    protected ReferenceType reference;

    /**
     * Contains the detailed documentation for a study unit which is a member of the group.
     * 
     * @return
     *     possible object is
     *     {@link ddi.studyunit._3_1.StudyUnitType }
     *     
     */
    public ddi.studyunit._3_1.StudyUnitType getStudyUnit() {
        return studyUnit;
    }

    /**
     * Sets the value of the studyUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ddi.studyunit._3_1.StudyUnitType }
     *     
     */
    public void setStudyUnit(ddi.studyunit._3_1.StudyUnitType value) {
        this.studyUnit = value;
    }

    /**
     * References a study unit which is a member of the group, but is documented in a different DDI metadata set.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setReference(ReferenceType value) {
        this.reference = value;
    }

}
