//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.physicaldataproduct_proprietary._3_1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ddi.physicaldataproduct._3_1.BaseRecordLayoutType;
import ddi.reusable._3_1.CodeValueType;
import ddi.reusable._3_1.DateTimeRepresentationType;
import ddi.reusable._3_1.NumericRepresentationType;
import ddi.reusable._3_1.ProprietaryInfoType;
import ddi.reusable._3_1.ReferenceType;
import ddi.reusable._3_1.SoftwareType;
import ddi.reusable._3_1.TextRepresentationType;


/**
 * A record layout for data in proprietary system files.
 * 
 * <p>Java class for ProprietaryRecordLayoutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProprietaryRecordLayoutType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:physicaldataproduct:3_1}BaseRecordLayoutType">
 *       &lt;sequence>
 *         &lt;element name="CharacterSet" type="{ddi:reusable:3_1}CodeValueType" minOccurs="0"/>
 *         &lt;element name="ArrayBase" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element ref="{ddi:reusable:3_1}Software"/>
 *         &lt;element ref="{ddi:physicaldataproduct_proprietary:3_1}DataItemAddress" minOccurs="0"/>
 *         &lt;element ref="{ddi:physicaldataproduct_proprietary:3_1}DefaultNumericDataType" minOccurs="0"/>
 *         &lt;element ref="{ddi:physicaldataproduct_proprietary:3_1}DefaultTextDataType" minOccurs="0"/>
 *         &lt;element ref="{ddi:physicaldataproduct_proprietary:3_1}DefaultDateTimeDataType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{ddi:physicaldataproduct_proprietary:3_1}CodedDataAsNumeric"/>
 *           &lt;element ref="{ddi:physicaldataproduct_proprietary:3_1}CodedDataAsText"/>
 *         &lt;/choice>
 *         &lt;element ref="{ddi:physicaldataproduct_proprietary:3_1}DefaultVariableSchemeReference"/>
 *         &lt;element ref="{ddi:reusable:3_1}ProprietaryInfo" minOccurs="0"/>
 *         &lt;element ref="{ddi:physicaldataproduct_proprietary:3_1}DataItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProprietaryRecordLayoutType", propOrder = {
    "characterSet",
    "arrayBase",
    "software",
    "dataItemAddress",
    "defaultNumericDataType",
    "defaultTextDataType",
    "defaultDateTimeDataType",
    "codedDataAsNumeric",
    "codedDataAsText",
    "defaultVariableSchemeReference",
    "proprietaryInfo",
    "dataItem"
})
public class ProprietaryRecordLayoutType
    extends BaseRecordLayoutType
{

    @XmlElement(name = "CharacterSet")
    protected CodeValueType characterSet;
    @XmlElement(name = "ArrayBase")
    protected BigInteger arrayBase;
    @XmlElement(name = "Software", namespace = "ddi:reusable:3_1", required = true)
    protected SoftwareType software;
    @XmlElement(name = "DataItemAddress")
    protected DataItemAddressType dataItemAddress;
    @XmlElement(name = "DefaultNumericDataType")
    protected NumericRepresentationType defaultNumericDataType;
    @XmlElement(name = "DefaultTextDataType")
    protected TextRepresentationType defaultTextDataType;
    @XmlElement(name = "DefaultDateTimeDataType")
    protected DateTimeRepresentationType defaultDateTimeDataType;
    @XmlElement(name = "CodedDataAsNumeric")
    protected NumericRepresentationType codedDataAsNumeric;
    @XmlElement(name = "CodedDataAsText")
    protected TextRepresentationType codedDataAsText;
    @XmlElement(name = "DefaultVariableSchemeReference", required = true)
    protected ReferenceType defaultVariableSchemeReference;
    @XmlElement(name = "ProprietaryInfo", namespace = "ddi:reusable:3_1")
    protected ProprietaryInfoType proprietaryInfo;
    @XmlElement(name = "DataItem")
    protected List<DataItemType> dataItem;

    /**
     * Gets the value of the characterSet property.
     * 
     * @return
     *     possible object is
     *     {@link CodeValueType }
     *     
     */
    public CodeValueType getCharacterSet() {
        return characterSet;
    }

    /**
     * Sets the value of the characterSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeValueType }
     *     
     */
    public void setCharacterSet(CodeValueType value) {
        this.characterSet = value;
    }

    /**
     * Gets the value of the arrayBase property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getArrayBase() {
        return arrayBase;
    }

    /**
     * Sets the value of the arrayBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setArrayBase(BigInteger value) {
        this.arrayBase = value;
    }

    /**
     * Software used by this record layout.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareType }
     *     
     */
    public SoftwareType getSoftware() {
        return software;
    }

    /**
     * Sets the value of the software property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareType }
     *     
     */
    public void setSoftware(SoftwareType value) {
        this.software = value;
    }

    /**
     * Provides minimum information on data item address system, such as variable ID or Name, etc.
     * 
     * @return
     *     possible object is
     *     {@link DataItemAddressType }
     *     
     */
    public DataItemAddressType getDataItemAddress() {
        return dataItemAddress;
    }

    /**
     * Sets the value of the dataItemAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataItemAddressType }
     *     
     */
    public void setDataItemAddress(DataItemAddressType value) {
        this.dataItemAddress = value;
    }

    /**
     * Declares the most common data type used for numeric data.
     * 
     * @return
     *     possible object is
     *     {@link NumericRepresentationType }
     *     
     */
    public NumericRepresentationType getDefaultNumericDataType() {
        return defaultNumericDataType;
    }

    /**
     * Sets the value of the defaultNumericDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericRepresentationType }
     *     
     */
    public void setDefaultNumericDataType(NumericRepresentationType value) {
        this.defaultNumericDataType = value;
    }

    /**
     * Declares the most common data type used for textual data.
     * 
     * @return
     *     possible object is
     *     {@link TextRepresentationType }
     *     
     */
    public TextRepresentationType getDefaultTextDataType() {
        return defaultTextDataType;
    }

    /**
     * Sets the value of the defaultTextDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextRepresentationType }
     *     
     */
    public void setDefaultTextDataType(TextRepresentationType value) {
        this.defaultTextDataType = value;
    }

    /**
     * Declares the most common data type used for date-time data.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeRepresentationType }
     *     
     */
    public DateTimeRepresentationType getDefaultDateTimeDataType() {
        return defaultDateTimeDataType;
    }

    /**
     * Sets the value of the defaultDateTimeDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeRepresentationType }
     *     
     */
    public void setDefaultDateTimeDataType(DateTimeRepresentationType value) {
        this.defaultDateTimeDataType = value;
    }

    /**
     * Indicates that coded data should be treated as numeric, and defines the numeric type
     * 
     * @return
     *     possible object is
     *     {@link NumericRepresentationType }
     *     
     */
    public NumericRepresentationType getCodedDataAsNumeric() {
        return codedDataAsNumeric;
    }

    /**
     * Sets the value of the codedDataAsNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericRepresentationType }
     *     
     */
    public void setCodedDataAsNumeric(NumericRepresentationType value) {
        this.codedDataAsNumeric = value;
    }

    /**
     * Indicates that coded data should be treated as text, and defines the text type
     * 
     * @return
     *     possible object is
     *     {@link TextRepresentationType }
     *     
     */
    public TextRepresentationType getCodedDataAsText() {
        return codedDataAsText;
    }

    /**
     * Sets the value of the codedDataAsText property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextRepresentationType }
     *     
     */
    public void setCodedDataAsText(TextRepresentationType value) {
        this.codedDataAsText = value;
    }

    /**
     * References the VariableScheme of the variables in the record. Can be overridden at the level of the DataItem.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getDefaultVariableSchemeReference() {
        return defaultVariableSchemeReference;
    }

    /**
     * Sets the value of the defaultVariableSchemeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setDefaultVariableSchemeReference(ReferenceType value) {
        this.defaultVariableSchemeReference = value;
    }

    /**
     * Contains information proprietary to the software package which produced the data file. This is expressed as a set of name-value pairs.
     * 
     * @return
     *     possible object is
     *     {@link ProprietaryInfoType }
     *     
     */
    public ProprietaryInfoType getProprietaryInfo() {
        return proprietaryInfo;
    }

    /**
     * Sets the value of the proprietaryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProprietaryInfoType }
     *     
     */
    public void setProprietaryInfo(ProprietaryInfoType value) {
        this.proprietaryInfo = value;
    }

    /**
     * Describes a data item in the record.Gets the value of the dataItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataItemType }
     * 
     * 
     */
    public List<DataItemType> getDataItem() {
        if (dataItem == null) {
            dataItem = new ArrayList<DataItemType>();
        }
        return this.dataItem;
    }

}
