//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.physicaldataproduct_ncube_normal._3_1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import ddi.reusable._3_1.ReferenceType;


/**
 * Reference to a measure description.
 * 
 * <p>Java class for MeasureReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasureReferenceType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:reusable:3_1}ReferenceType">
 *       &lt;attribute name="arrayOrder" type="{http://www.w3.org/2001/XMLSchema}integer" default="0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasureReferenceType")
public class MeasureReferenceType
    extends ReferenceType
{

    @XmlAttribute(name = "arrayOrder")
    protected BigInteger arrayOrder;

    /**
     * Gets the value of the arrayOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getArrayOrder() {
        if (arrayOrder == null) {
            return new BigInteger("0");
        } else {
            return arrayOrder;
        }
    }

    /**
     * Sets the value of the arrayOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setArrayOrder(BigInteger value) {
        this.arrayOrder = value;
    }

}
