//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.physicalinstance._3_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Includes a category-level statistic.
 * 
 * <p>Java class for CategoryStatisticsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoryStatisticsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CategoryValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{ddi:physicalinstance:3_1}CategoryStatistic" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryStatisticsType", propOrder = {
    "categoryValue",
    "categoryStatistic"
})
public class CategoryStatisticsType {

    @XmlElement(name = "CategoryValue", required = true)
    protected String categoryValue;
    @XmlElement(name = "CategoryStatistic", required = true)
    protected List<CategoryStatisticType> categoryStatistic;

    /**
     * Gets the value of the categoryValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryValue() {
        return categoryValue;
    }

    /**
     * Sets the value of the categoryValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryValue(String value) {
        this.categoryValue = value;
    }

    /**
     * Includes a statistic for the category value indicated in the sibling CategoryValue element.Gets the value of the categoryStatistic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoryStatistic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryStatistic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryStatisticType }
     * 
     * 
     */
    public List<CategoryStatisticType> getCategoryStatistic() {
        if (categoryStatistic == null) {
            categoryStatistic = new ArrayList<CategoryStatisticType>();
        }
        return this.categoryStatistic;
    }

}
