//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.physicalinstance._3_1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ddi.reusable._3_1.IdentifiableType;
import ddi.reusable._3_1.SoftwareType;
import ddi.reusable._3_1.StructuredStringType;


/**
 * Includes information about the file structure, as well as other characteristics that are specific to the physical instance.
 * 
 * <p>Java class for GrossFileStructureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GrossFileStructureType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:reusable:3_1}IdentifiableType">
 *       &lt;sequence>
 *         &lt;element name="PlaceOfProduction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{ddi:physicalinstance:3_1}ProcessingCheck" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProcessingStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{ddi:physicalinstance:3_1}CreationSoftware" minOccurs="0"/>
 *         &lt;element name="CaseQuantity" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="OverallRecordCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GrossFileStructureType", propOrder = {
    "placeOfProduction",
    "processingCheck",
    "processingStatus",
    "creationSoftware",
    "caseQuantity",
    "overallRecordCount"
})
public class GrossFileStructureType
    extends IdentifiableType
{

    @XmlElement(name = "PlaceOfProduction")
    protected String placeOfProduction;
    @XmlElement(name = "ProcessingCheck")
    protected List<StructuredStringType> processingCheck;
    @XmlElement(name = "ProcessingStatus")
    protected String processingStatus;
    @XmlElement(name = "CreationSoftware")
    protected SoftwareType creationSoftware;
    @XmlElement(name = "CaseQuantity")
    protected BigInteger caseQuantity;
    @XmlElement(name = "OverallRecordCount")
    protected BigInteger overallRecordCount;

    /**
     * Gets the value of the placeOfProduction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfProduction() {
        return placeOfProduction;
    }

    /**
     * Sets the value of the placeOfProduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfProduction(String value) {
        this.placeOfProduction = value;
    }

    /**
     * Documents processing checks and other operations performed on the data file.Gets the value of the processingCheck property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processingCheck property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessingCheck().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StructuredStringType }
     * 
     * 
     */
    public List<StructuredStringType> getProcessingCheck() {
        if (processingCheck == null) {
            processingCheck = new ArrayList<StructuredStringType>();
        }
        return this.processingCheck;
    }

    /**
     * Gets the value of the processingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingStatus() {
        return processingStatus;
    }

    /**
     * Sets the value of the processingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingStatus(String value) {
        this.processingStatus = value;
    }

    /**
     * Indicates the software that was used to create the data file.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareType }
     *     
     */
    public SoftwareType getCreationSoftware() {
        return creationSoftware;
    }

    /**
     * Sets the value of the creationSoftware property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareType }
     *     
     */
    public void setCreationSoftware(SoftwareType value) {
        this.creationSoftware = value;
    }

    /**
     * Gets the value of the caseQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCaseQuantity() {
        return caseQuantity;
    }

    /**
     * Sets the value of the caseQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCaseQuantity(BigInteger value) {
        this.caseQuantity = value;
    }

    /**
     * Gets the value of the overallRecordCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOverallRecordCount() {
        return overallRecordCount;
    }

    /**
     * Sets the value of the overallRecordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOverallRecordCount(BigInteger value) {
        this.overallRecordCount = value;
    }

}
