//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.physicalinstance._3_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import ddi.reusable._3_1.CodeValueType;
import ddi.reusable._3_1.ReferenceType;
import ddi.reusable._3_1.SoftwareType;
import ddi.reusable._3_1.StructuredStringType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ddi.physicalinstance._3_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StatisticalDataFileReference_QNAME = new QName("ddi:physicalinstance:3_1", "StatisticalDataFileReference");
    private final static QName _RecordLayoutReference_QNAME = new QName("ddi:physicalinstance:3_1", "RecordLayoutReference");
    private final static QName _CategoryStatisticTypeCoded_QNAME = new QName("ddi:physicalinstance:3_1", "CategoryStatisticTypeCoded");
    private final static QName _ByteOrder_QNAME = new QName("ddi:physicalinstance:3_1", "ByteOrder");
    private final static QName _FilterCategoryStatistic_QNAME = new QName("ddi:physicalinstance:3_1", "FilterCategoryStatistic");
    private final static QName _PhysicalInstance_QNAME = new QName("ddi:physicalinstance:3_1", "PhysicalInstance");
    private final static QName _DataFileIdentification_QNAME = new QName("ddi:physicalinstance:3_1", "DataFileIdentification");
    private final static QName _URI_QNAME = new QName("ddi:physicalinstance:3_1", "URI");
    private final static QName _SummaryStatisticTypeCoded_QNAME = new QName("ddi:physicalinstance:3_1", "SummaryStatisticTypeCoded");
    private final static QName _SummaryStatisticType_QNAME = new QName("ddi:physicalinstance:3_1", "SummaryStatisticType");
    private final static QName _DataFileReference_QNAME = new QName("ddi:physicalinstance:3_1", "DataFileReference");
    private final static QName _ExcludedMissingCategoryReference_QNAME = new QName("ddi:physicalinstance:3_1", "ExcludedMissingCategoryReference");
    private final static QName _Statistics_QNAME = new QName("ddi:physicalinstance:3_1", "Statistics");
    private final static QName _ProcessingCheck_QNAME = new QName("ddi:physicalinstance:3_1", "ProcessingCheck");
    private final static QName _CategoryStatistic_QNAME = new QName("ddi:physicalinstance:3_1", "CategoryStatistic");
    private final static QName _WeightUsedReference_QNAME = new QName("ddi:physicalinstance:3_1", "WeightUsedReference");
    private final static QName _CategoryStatistics_QNAME = new QName("ddi:physicalinstance:3_1", "CategoryStatistics");
    private final static QName _FilterCategoryStatistics_QNAME = new QName("ddi:physicalinstance:3_1", "FilterCategoryStatistics");
    private final static QName _SummaryStatistic_QNAME = new QName("ddi:physicalinstance:3_1", "SummaryStatistic");
    private final static QName _FilterVariableReference_QNAME = new QName("ddi:physicalinstance:3_1", "FilterVariableReference");
    private final static QName _WeightVariableReference_QNAME = new QName("ddi:physicalinstance:3_1", "WeightVariableReference");
    private final static QName _Fingerprint_QNAME = new QName("ddi:physicalinstance:3_1", "Fingerprint");
    private final static QName _CreationSoftware_QNAME = new QName("ddi:physicalinstance:3_1", "CreationSoftware");
    private final static QName _CategoryStatisticType_QNAME = new QName("ddi:physicalinstance:3_1", "CategoryStatisticType");
    private final static QName _Path_QNAME = new QName("ddi:physicalinstance:3_1", "Path");
    private final static QName _Filter_QNAME = new QName("ddi:physicalinstance:3_1", "Filter");
    private final static QName _VariableStatistics_QNAME = new QName("ddi:physicalinstance:3_1", "VariableStatistics");
    private final static QName _GrossFileStructure_QNAME = new QName("ddi:physicalinstance:3_1", "GrossFileStructure");
    private final static QName _VariableReference_QNAME = new QName("ddi:physicalinstance:3_1", "VariableReference");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ddi.physicalinstance._3_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SummaryStatisticType }
     * 
     */
    public SummaryStatisticType createSummaryStatisticType() {
        return new SummaryStatisticType();
    }

    /**
     * Create an instance of {@link StatisticsType }
     * 
     */
    public StatisticsType createStatisticsType() {
        return new StatisticsType();
    }

    /**
     * Create an instance of {@link SummaryStatisticTypeCodedType }
     * 
     */
    public SummaryStatisticTypeCodedType createSummaryStatisticTypeCodedType() {
        return new SummaryStatisticTypeCodedType();
    }

    /**
     * Create an instance of {@link FilterCategoryStatisticType }
     * 
     */
    public FilterCategoryStatisticType createFilterCategoryStatisticType() {
        return new FilterCategoryStatisticType();
    }

    /**
     * Create an instance of {@link PathType }
     * 
     */
    public PathType createPathType() {
        return new PathType();
    }

    /**
     * Create an instance of {@link FingerprintType }
     * 
     */
    public FingerprintType createFingerprintType() {
        return new FingerprintType();
    }

    /**
     * Create an instance of {@link CategoryStatisticType }
     * 
     */
    public CategoryStatisticType createCategoryStatisticType() {
        return new CategoryStatisticType();
    }

    /**
     * Create an instance of {@link GrossFileStructureType }
     * 
     */
    public GrossFileStructureType createGrossFileStructureType() {
        return new GrossFileStructureType();
    }

    /**
     * Create an instance of {@link URIType }
     * 
     */
    public URIType createURIType() {
        return new URIType();
    }

    /**
     * Create an instance of {@link FilterCategoryStatisticsType }
     * 
     */
    public FilterCategoryStatisticsType createFilterCategoryStatisticsType() {
        return new FilterCategoryStatisticsType();
    }

    /**
     * Create an instance of {@link CategoryStatisticsType }
     * 
     */
    public CategoryStatisticsType createCategoryStatisticsType() {
        return new CategoryStatisticsType();
    }

    /**
     * Create an instance of {@link StatisticalDataFileReferenceType }
     * 
     */
    public StatisticalDataFileReferenceType createStatisticalDataFileReferenceType() {
        return new StatisticalDataFileReferenceType();
    }

    /**
     * Create an instance of {@link FilterType }
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link CategoryStatisticTypeCodedType }
     * 
     */
    public CategoryStatisticTypeCodedType createCategoryStatisticTypeCodedType() {
        return new CategoryStatisticTypeCodedType();
    }

    /**
     * Create an instance of {@link DataFileIdentificationType }
     * 
     */
    public DataFileIdentificationType createDataFileIdentificationType() {
        return new DataFileIdentificationType();
    }

    /**
     * Create an instance of {@link PhysicalInstanceType }
     * 
     */
    public PhysicalInstanceType createPhysicalInstanceType() {
        return new PhysicalInstanceType();
    }

    /**
     * Create an instance of {@link VariableStatisticsType }
     * 
     */
    public VariableStatisticsType createVariableStatisticsType() {
        return new VariableStatisticsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticalDataFileReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "StatisticalDataFileReference")
    public JAXBElement<StatisticalDataFileReferenceType> createStatisticalDataFileReference(StatisticalDataFileReferenceType value) {
        return new JAXBElement<StatisticalDataFileReferenceType>(_StatisticalDataFileReference_QNAME, StatisticalDataFileReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "RecordLayoutReference")
    public JAXBElement<ReferenceType> createRecordLayoutReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_RecordLayoutReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryStatisticTypeCodedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "CategoryStatisticTypeCoded", substitutionHeadNamespace = "ddi:physicalinstance:3_1", substitutionHeadName = "CategoryStatisticType")
    public JAXBElement<CategoryStatisticTypeCodedType> createCategoryStatisticTypeCoded(CategoryStatisticTypeCodedType value) {
        return new JAXBElement<CategoryStatisticTypeCodedType>(_CategoryStatisticTypeCoded_QNAME, CategoryStatisticTypeCodedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "ByteOrder")
    public JAXBElement<CodeValueType> createByteOrder(CodeValueType value) {
        return new JAXBElement<CodeValueType>(_ByteOrder_QNAME, CodeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FilterCategoryStatisticType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "FilterCategoryStatistic")
    public JAXBElement<FilterCategoryStatisticType> createFilterCategoryStatistic(FilterCategoryStatisticType value) {
        return new JAXBElement<FilterCategoryStatisticType>(_FilterCategoryStatistic_QNAME, FilterCategoryStatisticType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PhysicalInstanceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "PhysicalInstance")
    public JAXBElement<PhysicalInstanceType> createPhysicalInstance(PhysicalInstanceType value) {
        return new JAXBElement<PhysicalInstanceType>(_PhysicalInstance_QNAME, PhysicalInstanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataFileIdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "DataFileIdentification")
    public JAXBElement<DataFileIdentificationType> createDataFileIdentification(DataFileIdentificationType value) {
        return new JAXBElement<DataFileIdentificationType>(_DataFileIdentification_QNAME, DataFileIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link URIType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "URI")
    public JAXBElement<URIType> createURI(URIType value) {
        return new JAXBElement<URIType>(_URI_QNAME, URIType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SummaryStatisticTypeCodedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "SummaryStatisticTypeCoded", substitutionHeadNamespace = "ddi:physicalinstance:3_1", substitutionHeadName = "SummaryStatisticType")
    public JAXBElement<SummaryStatisticTypeCodedType> createSummaryStatisticTypeCoded(SummaryStatisticTypeCodedType value) {
        return new JAXBElement<SummaryStatisticTypeCodedType>(_SummaryStatisticTypeCoded_QNAME, SummaryStatisticTypeCodedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "SummaryStatisticType")
    public JAXBElement<CodeValueType> createSummaryStatisticType(CodeValueType value) {
        return new JAXBElement<CodeValueType>(_SummaryStatisticType_QNAME, CodeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "DataFileReference")
    public JAXBElement<ReferenceType> createDataFileReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_DataFileReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "ExcludedMissingCategoryReference")
    public JAXBElement<ReferenceType> createExcludedMissingCategoryReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_ExcludedMissingCategoryReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "Statistics")
    public JAXBElement<StatisticsType> createStatistics(StatisticsType value) {
        return new JAXBElement<StatisticsType>(_Statistics_QNAME, StatisticsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "ProcessingCheck")
    public JAXBElement<StructuredStringType> createProcessingCheck(StructuredStringType value) {
        return new JAXBElement<StructuredStringType>(_ProcessingCheck_QNAME, StructuredStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryStatisticType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "CategoryStatistic")
    public JAXBElement<CategoryStatisticType> createCategoryStatistic(CategoryStatisticType value) {
        return new JAXBElement<CategoryStatisticType>(_CategoryStatistic_QNAME, CategoryStatisticType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "WeightUsedReference")
    public JAXBElement<ReferenceType> createWeightUsedReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_WeightUsedReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryStatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "CategoryStatistics")
    public JAXBElement<CategoryStatisticsType> createCategoryStatistics(CategoryStatisticsType value) {
        return new JAXBElement<CategoryStatisticsType>(_CategoryStatistics_QNAME, CategoryStatisticsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FilterCategoryStatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "FilterCategoryStatistics")
    public JAXBElement<FilterCategoryStatisticsType> createFilterCategoryStatistics(FilterCategoryStatisticsType value) {
        return new JAXBElement<FilterCategoryStatisticsType>(_FilterCategoryStatistics_QNAME, FilterCategoryStatisticsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SummaryStatisticType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "SummaryStatistic")
    public JAXBElement<SummaryStatisticType> createSummaryStatistic(SummaryStatisticType value) {
        return new JAXBElement<SummaryStatisticType>(_SummaryStatistic_QNAME, SummaryStatisticType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "FilterVariableReference")
    public JAXBElement<ReferenceType> createFilterVariableReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_FilterVariableReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "WeightVariableReference")
    public JAXBElement<ReferenceType> createWeightVariableReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_WeightVariableReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FingerprintType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "Fingerprint")
    public JAXBElement<FingerprintType> createFingerprint(FingerprintType value) {
        return new JAXBElement<FingerprintType>(_Fingerprint_QNAME, FingerprintType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoftwareType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "CreationSoftware")
    public JAXBElement<SoftwareType> createCreationSoftware(SoftwareType value) {
        return new JAXBElement<SoftwareType>(_CreationSoftware_QNAME, SoftwareType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "CategoryStatisticType")
    public JAXBElement<CodeValueType> createCategoryStatisticType(CodeValueType value) {
        return new JAXBElement<CodeValueType>(_CategoryStatisticType_QNAME, CodeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PathType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "Path")
    public JAXBElement<PathType> createPath(PathType value) {
        return new JAXBElement<PathType>(_Path_QNAME, PathType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FilterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "Filter")
    public JAXBElement<FilterType> createFilter(FilterType value) {
        return new JAXBElement<FilterType>(_Filter_QNAME, FilterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VariableStatisticsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "VariableStatistics")
    public JAXBElement<VariableStatisticsType> createVariableStatistics(VariableStatisticsType value) {
        return new JAXBElement<VariableStatisticsType>(_VariableStatistics_QNAME, VariableStatisticsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GrossFileStructureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "GrossFileStructure")
    public JAXBElement<GrossFileStructureType> createGrossFileStructure(GrossFileStructureType value) {
        return new JAXBElement<GrossFileStructureType>(_GrossFileStructure_QNAME, GrossFileStructureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:physicalinstance:3_1", name = "VariableReference")
    public JAXBElement<ReferenceType> createVariableReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_VariableReference_QNAME, ReferenceType.class, null, value);
    }

}
