//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.logicalproduct._3_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import ddi.reusable._3_1.CodeValueType;


/**
 * A suggested enumeration of group types. Indicates reasons for grouping. 
 * 
 * <p>Java class for GroupTypeCodedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroupTypeCodedType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;ddi:reusable:3_1>CodeValueType">
 *       &lt;attribute name="codeListID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="Group Type" />
 *       &lt;attribute name="codeListAgencyName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="DDI" />
 *       &lt;attribute name="codeListVersionID" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.0" />
 *       &lt;attribute name="otherValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupTypeCodedType")
public class GroupTypeCodedType
    extends CodeValueType
{


}
