//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.reusable._3_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Used to identify described identifiable objects for purposes of internal and/or external referencing. Elements of this type cannot be versioned or maintained except as part of a complex parent element. Provides containers for Uniform Resource Name (URN) as well as ID information. An entity can either be identified by a URN, or an ID. The Agency and Version information in the URN is inherited from the containing elements. If both URN and combination of elements is used, the URN takes precedence. The element can be designated as an addition, replacement, or deletion to facilitate tracking changes.
 * 
 * <p>Java class for AbstractIdentifiableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractIdentifiableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:reusable:3_1}UserID" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{ddi:reusable:3_1}BaseIDType" />
 *       &lt;attribute name="urn" type="{ddi:reusable:3_1}DDIURNType" />
 *       &lt;attribute name="action" type="{ddi:reusable:3_1}ActionCodeType" />
 *       &lt;attribute name="objectSource" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractIdentifiableType", propOrder = {
    "userID"
})
@XmlSeeAlso({
    IdentifiableType.class,
    AbstractVersionableType.class
})
public abstract class AbstractIdentifiableType {

    @XmlElement(name = "UserID")
    protected List<UserIDType> userID;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "urn")
    protected String urn;
    @XmlAttribute(name = "action")
    protected ActionCodeType action;
    @XmlAttribute(name = "objectSource")
    @XmlSchemaType(name = "anyURI")
    protected String objectSource;

    /**
     * An identifer that is locally unique within its specifc type. The required type attribute points to the local user identification system that defines the values. If multiple UserIDs are used they must be differentiated by the type attribute.Gets the value of the userID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserIDType }
     * 
     * 
     */
    public List<UserIDType> getUserID() {
        if (userID == null) {
            userID = new ArrayList<UserIDType>();
        }
        return this.userID;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the urn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrn() {
        return urn;
    }

    /**
     * Sets the value of the urn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrn(String value) {
        this.urn = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionCodeType }
     *     
     */
    public ActionCodeType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionCodeType }
     *     
     */
    public void setAction(ActionCodeType value) {
        this.action = value;
    }

    /**
     * Gets the value of the objectSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectSource() {
        return objectSource;
    }

    /**
     * Sets the value of the objectSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectSource(String value) {
        this.objectSource = value;
    }

}
