//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.reusable._3_1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Set of north, south, east, west coordinates defining a rectangle that encompasses the full extent of geographic coverage.
 * 
 * <p>Java class for BoundingBoxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BoundingBoxType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:reusable:3_1}WestLongitude"/>
 *         &lt;element ref="{ddi:reusable:3_1}EastLongitude"/>
 *         &lt;element ref="{ddi:reusable:3_1}SouthLatitude"/>
 *         &lt;element ref="{ddi:reusable:3_1}NorthLatitude"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoundingBoxType", propOrder = {
    "westLongitude",
    "eastLongitude",
    "southLatitude",
    "northLatitude"
})
public class BoundingBoxType {

    @XmlElement(name = "WestLongitude", required = true)
    protected BigDecimal westLongitude;
    @XmlElement(name = "EastLongitude", required = true)
    protected BigDecimal eastLongitude;
    @XmlElement(name = "SouthLatitude", required = true)
    protected BigDecimal southLatitude;
    @XmlElement(name = "NorthLatitude", required = true)
    protected BigDecimal northLatitude;

    /**
     * West longitude of the bounding box. (xmin)
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWestLongitude() {
        return westLongitude;
    }

    /**
     * Sets the value of the westLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWestLongitude(BigDecimal value) {
        this.westLongitude = value;
    }

    /**
     * East longitude of the bounding box. (xmax)
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEastLongitude() {
        return eastLongitude;
    }

    /**
     * Sets the value of the eastLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEastLongitude(BigDecimal value) {
        this.eastLongitude = value;
    }

    /**
     * South latitude of the bounding box. (ymin)
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSouthLatitude() {
        return southLatitude;
    }

    /**
     * Sets the value of the southLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSouthLatitude(BigDecimal value) {
        this.southLatitude = value;
    }

    /**
     * North latitude of the bounding box. (ymax)
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNorthLatitude() {
        return northLatitude;
    }

    /**
     * Sets the value of the northLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNorthLatitude(BigDecimal value) {
        this.northLatitude = value;
    }

}
