//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.reusable._3_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A complete structure to describe formal transformation procedures of variables. This could be an XML structure like MathML or a simple string.
 * 
 * <p>Java class for CommandType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommandType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CommandText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{ddi:reusable:3_1}CommandFile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{ddi:reusable:3_1}StructuredCommand" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="formalLanguage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommandType", propOrder = {
    "commandText",
    "commandFile",
    "structuredCommand"
})
public class CommandType {

    @XmlElement(name = "CommandText")
    protected String commandText;
    @XmlElement(name = "CommandFile")
    protected List<CommandFileType> commandFile;
    @XmlElement(name = "StructuredCommand")
    protected StructuredCommandType structuredCommand;
    @XmlAttribute(name = "formalLanguage")
    protected String formalLanguage;

    /**
     * Gets the value of the commandText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandText() {
        return commandText;
    }

    /**
     * Sets the value of the commandText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandText(String value) {
        this.commandText = value;
    }

    /**
     * An etxernal file containing the commands for creating the generation.Gets the value of the commandFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commandFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommandFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommandFileType }
     * 
     * 
     */
    public List<CommandFileType> getCommandFile() {
        if (commandFile == null) {
            commandFile = new ArrayList<CommandFileType>();
        }
        return this.commandFile;
    }

    /**
     * Used to insert extensions to provide structured language for external namespaces such as MathML.
     * 
     * @return
     *     possible object is
     *     {@link StructuredCommandType }
     *     
     */
    public StructuredCommandType getStructuredCommand() {
        return structuredCommand;
    }

    /**
     * Sets the value of the structuredCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructuredCommandType }
     *     
     */
    public void setStructuredCommand(StructuredCommandType value) {
        this.structuredCommand = value;
    }

    /**
     * Gets the value of the formalLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormalLanguage() {
        return formalLanguage;
    }

    /**
     * Sets the value of the formalLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormalLanguage(String value) {
        this.formalLanguage = value;
    }

}
