//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.reusable._3_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import ddi.datacollection._3_1.GeographicDomainType;


/**
 * Structures the representation for a geographic point to ensure collection of relevant information. The point may be associated with a polygon (such as the centroid of the polygon) or a line (end or shape points of a line).
 * 
 * <p>Java class for GeographicRepresentationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeographicRepresentationType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:reusable:3_1}RepresentationType">
 *       &lt;sequence>
 *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}NCName"/>
 *         &lt;element name="CoordinateSystem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CoordinateZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CoordinateSource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ErrorCorrection" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Offset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GeoreferencedObject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AddressMatchType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{ddi:reusable:3_1}CoordinatePairs" maxOccurs="unbounded"/>
 *         &lt;element ref="{ddi:reusable:3_1}AlternateOffset" minOccurs="0"/>
 *         &lt;element ref="{ddi:reusable:3_1}AlternateObject" minOccurs="0"/>
 *         &lt;element ref="{ddi:reusable:3_1}AlternateCoordinateSystem" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="format" use="required" type="{ddi:reusable:3_1}PointFormatType" />
 *       &lt;attribute name="spatialPrimitive" use="required" type="{ddi:reusable:3_1}GeographicDescriptionCodeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeographicRepresentationType", propOrder = {
    "datum",
    "coordinateSystem",
    "coordinateZone",
    "coordinateSource",
    "errorCorrection",
    "offset",
    "georeferencedObject",
    "addressMatchType",
    "coordinatePairs",
    "alternateOffset",
    "alternateObject",
    "alternateCoordinateSystem"
})
@XmlSeeAlso({
    GeographicDomainType.class
})
public class GeographicRepresentationType
    extends RepresentationType
{

    @XmlElement(name = "Datum", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String datum;
    @XmlElement(name = "CoordinateSystem", required = true)
    protected String coordinateSystem;
    @XmlElement(name = "CoordinateZone")
    protected String coordinateZone;
    @XmlElement(name = "CoordinateSource", required = true)
    protected String coordinateSource;
    @XmlElement(name = "ErrorCorrection", required = true)
    protected String errorCorrection;
    @XmlElement(name = "Offset", required = true)
    protected String offset;
    @XmlElement(name = "GeoreferencedObject", required = true)
    protected String georeferencedObject;
    @XmlElement(name = "AddressMatchType")
    protected String addressMatchType;
    @XmlElement(name = "CoordinatePairs", required = true)
    protected List<CoordinatePairsType> coordinatePairs;
    @XmlElement(name = "AlternateOffset")
    protected TextDomainType alternateOffset;
    @XmlElement(name = "AlternateObject")
    protected TextDomainType alternateObject;
    @XmlElement(name = "AlternateCoordinateSystem")
    protected TextDomainType alternateCoordinateSystem;
    @XmlAttribute(name = "format", required = true)
    protected PointFormatType format;
    @XmlAttribute(name = "spatialPrimitive", required = true)
    protected GeographicDescriptionCodeType spatialPrimitive;

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the coordinateSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordinateSystem() {
        return coordinateSystem;
    }

    /**
     * Sets the value of the coordinateSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordinateSystem(String value) {
        this.coordinateSystem = value;
    }

    /**
     * Gets the value of the coordinateZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordinateZone() {
        return coordinateZone;
    }

    /**
     * Sets the value of the coordinateZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordinateZone(String value) {
        this.coordinateZone = value;
    }

    /**
     * Gets the value of the coordinateSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordinateSource() {
        return coordinateSource;
    }

    /**
     * Sets the value of the coordinateSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordinateSource(String value) {
        this.coordinateSource = value;
    }

    /**
     * Gets the value of the errorCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCorrection() {
        return errorCorrection;
    }

    /**
     * Sets the value of the errorCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCorrection(String value) {
        this.errorCorrection = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffset(String value) {
        this.offset = value;
    }

    /**
     * Gets the value of the georeferencedObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeoreferencedObject() {
        return georeferencedObject;
    }

    /**
     * Sets the value of the georeferencedObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeoreferencedObject(String value) {
        this.georeferencedObject = value;
    }

    /**
     * Gets the value of the addressMatchType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressMatchType() {
        return addressMatchType;
    }

    /**
     * Sets the value of the addressMatchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressMatchType(String value) {
        this.addressMatchType = value;
    }

    /**
     * Field to capture coordinate pairs as individual pairs or as an array of pairs.Gets the value of the coordinatePairs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordinatePairs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoordinatePairs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinatePairsType }
     * 
     * 
     */
    public List<CoordinatePairsType> getCoordinatePairs() {
        if (coordinatePairs == null) {
            coordinatePairs = new ArrayList<CoordinatePairsType>();
        }
        return this.coordinatePairs;
    }

    /**
     * Allows entry of a non-standard offset figure.
     * 
     * @return
     *     possible object is
     *     {@link TextDomainType }
     *     
     */
    public TextDomainType getAlternateOffset() {
        return alternateOffset;
    }

    /**
     * Sets the value of the alternateOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextDomainType }
     *     
     */
    public void setAlternateOffset(TextDomainType value) {
        this.alternateOffset = value;
    }

    /**
     * Allows identification of an alternate object when the default object is not measureable.
     * 
     * @return
     *     possible object is
     *     {@link TextDomainType }
     *     
     */
    public TextDomainType getAlternateObject() {
        return alternateObject;
    }

    /**
     * Sets the value of the alternateObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextDomainType }
     *     
     */
    public void setAlternateObject(TextDomainType value) {
        this.alternateObject = value;
    }

    /**
     * Allows collection of data for a case in a different coordinate system than stated in the response structure.
     * 
     * @return
     *     possible object is
     *     {@link TextDomainType }
     *     
     */
    public TextDomainType getAlternateCoordinateSystem() {
        return alternateCoordinateSystem;
    }

    /**
     * Sets the value of the alternateCoordinateSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextDomainType }
     *     
     */
    public void setAlternateCoordinateSystem(TextDomainType value) {
        this.alternateCoordinateSystem = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link PointFormatType }
     *     
     */
    public PointFormatType getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointFormatType }
     *     
     */
    public void setFormat(PointFormatType value) {
        this.format = value;
    }

    /**
     * Gets the value of the spatialPrimitive property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicDescriptionCodeType }
     *     
     */
    public GeographicDescriptionCodeType getSpatialPrimitive() {
        return spatialPrimitive;
    }

    /**
     * Sets the value of the spatialPrimitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicDescriptionCodeType }
     *     
     */
    public void setSpatialPrimitive(GeographicDescriptionCodeType value) {
        this.spatialPrimitive = value;
    }

}
