//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.reusable._3_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Provides a reference to a described geographic level and a human-readable name for the level.
 * 
 * <p>Java class for LevelReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LevelReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{ddi:reusable:3_1}LevelReference" minOccurs="0"/>
 *         &lt;element name="LevelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LevelReferenceType", propOrder = {
    "levelReferenceAndLevelName"
})
public class LevelReferenceType {

    @XmlElements({
        @XmlElement(name = "LevelReference", type = ReferenceType.class),
        @XmlElement(name = "LevelName", type = String.class)
    })
    protected List<Object> levelReferenceAndLevelName;

    /**
     * Gets the value of the levelReferenceAndLevelName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the levelReferenceAndLevelName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLevelReferenceAndLevelName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceType }
     * {@link String }
     * 
     * 
     */
    public List<Object> getLevelReferenceAndLevelName() {
        if (levelReferenceAndLevelName == null) {
            levelReferenceAndLevelName = new ArrayList<Object>();
        }
        return this.levelReferenceAndLevelName;
    }

}
