//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.reusable._3_1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structures a numeric range. the regExp attribute holds a regular expression (same as for W3C XML Schema simple types) which can provide a filter for the contents.
 * 
 * <p>Java class for NumberRangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NumberRangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:reusable:3_1}Low" minOccurs="0"/>
 *         &lt;element ref="{ddi:reusable:3_1}High" minOccurs="0"/>
 *         &lt;element name="TopCode" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="BottomCode" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="regExp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumberRangeType", propOrder = {
    "low",
    "high",
    "topCode",
    "bottomCode"
})
public class NumberRangeType {

    @XmlElement(name = "Low")
    protected NumberRangeValueType low;
    @XmlElement(name = "High")
    protected NumberRangeValueType high;
    @XmlElement(name = "TopCode")
    protected BigDecimal topCode;
    @XmlElement(name = "BottomCode")
    protected BigDecimal bottomCode;
    @XmlAttribute(name = "regExp")
    protected String regExp;

    /**
     * The lower bound of the range. If not present, then there is no lower bound.
     * 
     * @return
     *     possible object is
     *     {@link NumberRangeValueType }
     *     
     */
    public NumberRangeValueType getLow() {
        return low;
    }

    /**
     * Sets the value of the low property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberRangeValueType }
     *     
     */
    public void setLow(NumberRangeValueType value) {
        this.low = value;
    }

    /**
     * The upper bound of the range. If not present, then there is no upper bound.
     * 
     * @return
     *     possible object is
     *     {@link NumberRangeValueType }
     *     
     */
    public NumberRangeValueType getHigh() {
        return high;
    }

    /**
     * Sets the value of the high property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberRangeValueType }
     *     
     */
    public void setHigh(NumberRangeValueType value) {
        this.high = value;
    }

    /**
     * Gets the value of the topCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTopCode() {
        return topCode;
    }

    /**
     * Sets the value of the topCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTopCode(BigDecimal value) {
        this.topCode = value;
    }

    /**
     * Gets the value of the bottomCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBottomCode() {
        return bottomCode;
    }

    /**
     * Sets the value of the bottomCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBottomCode(BigDecimal value) {
        this.bottomCode = value;
    }

    /**
     * Gets the value of the regExp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegExp() {
        return regExp;
    }

    /**
     * Sets the value of the regExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegExp(String value) {
        this.regExp = value;
    }

}
