//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.reusable._3_1;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ddi.reusable._3_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GeographyCode_QNAME = new QName("ddi:reusable:3_1", "GeographyCode");
    private final static QName _SouthLatitude_QNAME = new QName("ddi:reusable:3_1", "SouthLatitude");
    private final static QName _AuthorityOrganizationReference_QNAME = new QName("ddi:reusable:3_1", "AuthorityOrganizationReference");
    private final static QName _HistoricalDate_QNAME = new QName("ddi:reusable:3_1", "HistoricalDate");
    private final static QName _AlternateObject_QNAME = new QName("ddi:reusable:3_1", "AlternateObject");
    private final static QName _ImageArea_QNAME = new QName("ddi:reusable:3_1", "ImageArea");
    private final static QName _LineParameter_QNAME = new QName("ddi:reusable:3_1", "LineParameter");
    private final static QName _Date_QNAME = new QName("ddi:reusable:3_1", "Date");
    private final static QName _StartDate_QNAME = new QName("ddi:reusable:3_1", "StartDate");
    private final static QName _TemporalCoverage_QNAME = new QName("ddi:reusable:3_1", "TemporalCoverage");
    private final static QName _YCoordinate_QNAME = new QName("ddi:reusable:3_1", "YCoordinate");
    private final static QName _TopicalCoverageReference_QNAME = new QName("ddi:reusable:3_1", "TopicalCoverageReference");
    private final static QName _SoftwarePackage_QNAME = new QName("ddi:reusable:3_1", "SoftwarePackage");
    private final static QName _Audio_QNAME = new QName("ddi:reusable:3_1", "Audio");
    private final static QName _ProprietaryProperty_QNAME = new QName("ddi:reusable:3_1", "ProprietaryProperty");
    private final static QName _CommandFile_QNAME = new QName("ddi:reusable:3_1", "CommandFile");
    private final static QName _Scheme_QNAME = new QName("ddi:reusable:3_1", "Scheme");
    private final static QName _Copyright_QNAME = new QName("ddi:reusable:3_1", "Copyright");
    private final static QName _URN_QNAME = new QName("ddi:reusable:3_1", "URN");
    private final static QName _DefaultDecimalSeparator_QNAME = new QName("ddi:reusable:3_1", "DefaultDecimalSeparator");
    private final static QName _EastLongitude_QNAME = new QName("ddi:reusable:3_1", "EastLongitude");
    private final static QName _GeographyValue_QNAME = new QName("ddi:reusable:3_1", "GeographyValue");
    private final static QName _Name_QNAME = new QName("ddi:reusable:3_1", "Name");
    private final static QName _LifecycleEvent_QNAME = new QName("ddi:reusable:3_1", "LifecycleEvent");
    private final static QName _AlternateTitle_QNAME = new QName("ddi:reusable:3_1", "AlternateTitle");
    private final static QName _EnforcementAgencyOrganizationReference_QNAME = new QName("ddi:reusable:3_1", "EnforcementAgencyOrganizationReference");
    private final static QName _SchemeReference_QNAME = new QName("ddi:reusable:3_1", "SchemeReference");
    private final static QName _GeographyStructureVariable_QNAME = new QName("ddi:reusable:3_1", "GeographyStructureVariable");
    private final static QName _Low_QNAME = new QName("ddi:reusable:3_1", "Low");
    private final static QName _GeographicLocation_QNAME = new QName("ddi:reusable:3_1", "GeographicLocation");
    private final static QName _XCoordinate_QNAME = new QName("ddi:reusable:3_1", "XCoordinate");
    private final static QName _VideoClipType_QNAME = new QName("ddi:reusable:3_1", "VideoClipType");
    private final static QName _GeographicTime_QNAME = new QName("ddi:reusable:3_1", "GeographicTime");
    private final static QName _GeographicLevelReference_QNAME = new QName("ddi:reusable:3_1", "GeographicLevelReference");
    private final static QName _InternationalIdentifier_QNAME = new QName("ddi:reusable:3_1", "InternationalIdentifier");
    private final static QName _Values_QNAME = new QName("ddi:reusable:3_1", "Values");
    private final static QName _LifecycleInformation_QNAME = new QName("ddi:reusable:3_1", "LifecycleInformation");
    private final static QName _GeographicStructureReference_QNAME = new QName("ddi:reusable:3_1", "GeographicStructureReference");
    private final static QName _SeriesName_QNAME = new QName("ddi:reusable:3_1", "SeriesName");
    private final static QName _High_QNAME = new QName("ddi:reusable:3_1", "High");
    private final static QName _SourceQuestionReference_QNAME = new QName("ddi:reusable:3_1", "SourceQuestionReference");
    private final static QName _GeographicLevelDescription_QNAME = new QName("ddi:reusable:3_1", "GeographicLevelDescription");
    private final static QName _Label_QNAME = new QName("ddi:reusable:3_1", "Label");
    private final static QName _Subject_QNAME = new QName("ddi:reusable:3_1", "Subject");
    private final static QName _RelationshipDescription_QNAME = new QName("ddi:reusable:3_1", "RelationshipDescription");
    private final static QName _Title_QNAME = new QName("ddi:reusable:3_1", "Title");
    private final static QName _Note_QNAME = new QName("ddi:reusable:3_1", "Note");
    private final static QName _Image_QNAME = new QName("ddi:reusable:3_1", "Image");
    private final static QName _SpatialObject_QNAME = new QName("ddi:reusable:3_1", "SpatialObject");
    private final static QName _Code_QNAME = new QName("ddi:reusable:3_1", "Code");
    private final static QName _UserID_QNAME = new QName("ddi:reusable:3_1", "UserID");
    private final static QName _ParentGeography_QNAME = new QName("ddi:reusable:3_1", "ParentGeography");
    private final static QName _RelationshipDescripton_QNAME = new QName("ddi:reusable:3_1", "RelationshipDescripton");
    private final static QName _EndDate_QNAME = new QName("ddi:reusable:3_1", "EndDate");
    private final static QName _MaximumValue_QNAME = new QName("ddi:reusable:3_1", "MaximumValue");
    private final static QName _GeographyName_QNAME = new QName("ddi:reusable:3_1", "GeographyName");
    private final static QName _HistoricalStartDate_QNAME = new QName("ddi:reusable:3_1", "HistoricalStartDate");
    private final static QName _Video_QNAME = new QName("ddi:reusable:3_1", "Video");
    private final static QName _AnalysisUnit_QNAME = new QName("ddi:reusable:3_1", "AnalysisUnit");
    private final static QName _SubTitle_QNAME = new QName("ddi:reusable:3_1", "SubTitle");
    private final static QName _FundingInformation_QNAME = new QName("ddi:reusable:3_1", "FundingInformation");
    private final static QName _Version_QNAME = new QName("ddi:reusable:3_1", "Version");
    private final static QName _Add_QNAME = new QName("ddi:reusable:3_1", "Add");
    private final static QName _Shape_QNAME = new QName("ddi:reusable:3_1", "Shape");
    private final static QName _BoundingPolygon_QNAME = new QName("ddi:reusable:3_1", "BoundingPolygon");
    private final static QName _AlternateCoordinateSystem_QNAME = new QName("ddi:reusable:3_1", "AlternateCoordinateSystem");
    private final static QName _CategorySchemeReference_QNAME = new QName("ddi:reusable:3_1", "CategorySchemeReference");
    private final static QName _RelatedToReference_QNAME = new QName("ddi:reusable:3_1", "RelatedToReference");
    private final static QName _Description_QNAME = new QName("ddi:reusable:3_1", "Description");
    private final static QName _Citation_QNAME = new QName("ddi:reusable:3_1", "Citation");
    private final static QName _ExcludingPolygon_QNAME = new QName("ddi:reusable:3_1", "ExcludingPolygon");
    private final static QName _Rationale_QNAME = new QName("ddi:reusable:3_1", "Rationale");
    private final static QName _Geography_QNAME = new QName("ddi:reusable:3_1", "Geography");
    private final static QName _AudioClipType_QNAME = new QName("ddi:reusable:3_1", "AudioClipType");
    private final static QName _Publisher_QNAME = new QName("ddi:reusable:3_1", "Publisher");
    private final static QName _SeriesDescription_QNAME = new QName("ddi:reusable:3_1", "SeriesDescription");
    private final static QName _TopCode_QNAME = new QName("ddi:reusable:3_1", "TopCode");
    private final static QName _Coverage_QNAME = new QName("ddi:reusable:3_1", "Coverage");
    private final static QName _CoverageLimitation_QNAME = new QName("ddi:reusable:3_1", "CoverageLimitation");
    private final static QName _Module_QNAME = new QName("ddi:reusable:3_1", "Module");
    private final static QName _Segment_QNAME = new QName("ddi:reusable:3_1", "Segment");
    private final static QName _AlternateOffset_QNAME = new QName("ddi:reusable:3_1", "AlternateOffset");
    private final static QName _SummaryDataReference_QNAME = new QName("ddi:reusable:3_1", "SummaryDataReference");
    private final static QName _GeographyReference_QNAME = new QName("ddi:reusable:3_1", "GeographyReference");
    private final static QName _CharacterParameter_QNAME = new QName("ddi:reusable:3_1", "CharacterParameter");
    private final static QName _BoundingBox_QNAME = new QName("ddi:reusable:3_1", "BoundingBox");
    private final static QName _Relationship_QNAME = new QName("ddi:reusable:3_1", "Relationship");
    private final static QName _ProprietaryInfo_QNAME = new QName("ddi:reusable:3_1", "ProprietaryInfo");
    private final static QName _SpatialCoverage_QNAME = new QName("ddi:reusable:3_1", "SpatialCoverage");
    private final static QName _Embargo_QNAME = new QName("ddi:reusable:3_1", "Embargo");
    private final static QName _VersionRationale_QNAME = new QName("ddi:reusable:3_1", "VersionRationale");
    private final static QName _ID_QNAME = new QName("ddi:reusable:3_1", "ID");
    private final static QName _Delete_QNAME = new QName("ddi:reusable:3_1", "Delete");
    private final static QName _TemporalCoverageReference_QNAME = new QName("ddi:reusable:3_1", "TemporalCoverageReference");
    private final static QName _DefaultDigitGroupSeparator_QNAME = new QName("ddi:reusable:3_1", "DefaultDigitGroupSeparator");
    private final static QName _AgencyOrganizationReference_QNAME = new QName("ddi:reusable:3_1", "AgencyOrganizationReference");
    private final static QName _NorthLatitude_QNAME = new QName("ddi:reusable:3_1", "NorthLatitude");
    private final static QName _Replace_QNAME = new QName("ddi:reusable:3_1", "Replace");
    private final static QName _Level_QNAME = new QName("ddi:reusable:3_1", "Level");
    private final static QName _GeographicLocationReference_QNAME = new QName("ddi:reusable:3_1", "GeographicLocationReference");
    private final static QName _Creator_QNAME = new QName("ddi:reusable:3_1", "Creator");
    private final static QName _SpatialCoverageReference_QNAME = new QName("ddi:reusable:3_1", "SpatialCoverageReference");
    private final static QName _PublicationDate_QNAME = new QName("ddi:reusable:3_1", "PublicationDate");
    private final static QName _MinimumValue_QNAME = new QName("ddi:reusable:3_1", "MinimumValue");
    private final static QName _Reason_QNAME = new QName("ddi:reusable:3_1", "Reason");
    private final static QName _TimeZone_QNAME = new QName("ddi:reusable:3_1", "TimeZone");
    private final static QName _StructuredCommand_QNAME = new QName("ddi:reusable:3_1", "StructuredCommand");
    private final static QName _GeographicLayerBase_QNAME = new QName("ddi:reusable:3_1", "GeographicLayerBase");
    private final static QName _CoordinatePairs_QNAME = new QName("ddi:reusable:3_1", "CoordinatePairs");
    private final static QName _Exclude_QNAME = new QName("ddi:reusable:3_1", "Exclude");
    private final static QName _Point_QNAME = new QName("ddi:reusable:3_1", "Point");
    private final static QName _User_QNAME = new QName("ddi:reusable:3_1", "User");
    private final static QName _TopLevelReference_QNAME = new QName("ddi:reusable:3_1", "TopLevelReference");
    private final static QName _Textual_QNAME = new QName("ddi:reusable:3_1", "Textual");
    private final static QName _SeriesStatement_QNAME = new QName("ddi:reusable:3_1", "SeriesStatement");
    private final static QName _Content_QNAME = new QName("ddi:reusable:3_1", "Content");
    private final static QName _CodeSchemeReference_QNAME = new QName("ddi:reusable:3_1", "CodeSchemeReference");
    private final static QName _VersionDate_QNAME = new QName("ddi:reusable:3_1", "VersionDate");
    private final static QName _LevelReference_QNAME = new QName("ddi:reusable:3_1", "LevelReference");
    private final static QName _VariableReference_QNAME = new QName("ddi:reusable:3_1", "VariableReference");
    private final static QName _SimpleDate_QNAME = new QName("ddi:reusable:3_1", "SimpleDate");
    private final static QName _WestLongitude_QNAME = new QName("ddi:reusable:3_1", "WestLongitude");
    private final static QName _TopicalCoverage_QNAME = new QName("ddi:reusable:3_1", "TopicalCoverage");
    private final static QName _UniverseReference_QNAME = new QName("ddi:reusable:3_1", "UniverseReference");
    private final static QName _EventType_QNAME = new QName("ddi:reusable:3_1", "EventType");
    private final static QName _LowestLevelReference_QNAME = new QName("ddi:reusable:3_1", "LowestLevelReference");
    private final static QName _GeographicStructure_QNAME = new QName("ddi:reusable:3_1", "GeographicStructure");
    private final static QName _Software_QNAME = new QName("ddi:reusable:3_1", "Software");
    private final static QName _ReferenceDate_QNAME = new QName("ddi:reusable:3_1", "ReferenceDate");
    private final static QName _Contributor_QNAME = new QName("ddi:reusable:3_1", "Contributor");
    private final static QName _OtherMaterial_QNAME = new QName("ddi:reusable:3_1", "OtherMaterial");
    private final static QName _EmbargoName_QNAME = new QName("ddi:reusable:3_1", "EmbargoName");
    private final static QName _HistoricalEndDate_QNAME = new QName("ddi:reusable:3_1", "HistoricalEndDate");
    private final static QName _NumberRange_QNAME = new QName("ddi:reusable:3_1", "NumberRange");
    private final static QName _Command_QNAME = new QName("ddi:reusable:3_1", "Command");
    private final static QName _Keyword_QNAME = new QName("ddi:reusable:3_1", "Keyword");
    private final static QName _ReferenceTypeIdentifyingAgency_QNAME = new QName("ddi:reusable:3_1", "IdentifyingAgency");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ddi.reusable._3_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InternationalStringType }
     * 
     */
    public InternationalStringType createInternationalStringType() {
        return new InternationalStringType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link StructuredStringType }
     * 
     */
    public StructuredStringType createStructuredStringType() {
        return new StructuredStringType();
    }

    /**
     * Create an instance of {@link EmailType }
     * 
     */
    public EmailType createEmailType() {
        return new EmailType();
    }

    /**
     * Create an instance of {@link AccessRestrictionDateType }
     * 
     */
    public AccessRestrictionDateType createAccessRestrictionDateType() {
        return new AccessRestrictionDateType();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link CodeValueType }
     * 
     */
    public CodeValueType createCodeValueType() {
        return new CodeValueType();
    }

    /**
     * Create an instance of {@link PointType }
     * 
     */
    public PointType createPointType() {
        return new PointType();
    }

    /**
     * Create an instance of {@link SchemeReferenceType }
     * 
     */
    public SchemeReferenceType createSchemeReferenceType() {
        return new SchemeReferenceType();
    }

    /**
     * Create an instance of {@link SpatialCoordinateType }
     * 
     */
    public SpatialCoordinateType createSpatialCoordinateType() {
        return new SpatialCoordinateType();
    }

    /**
     * Create an instance of {@link CoverageType }
     * 
     */
    public CoverageType createCoverageType() {
        return new CoverageType();
    }

    /**
     * Create an instance of {@link TemporalCoverageType }
     * 
     */
    public TemporalCoverageType createTemporalCoverageType() {
        return new TemporalCoverageType();
    }

    /**
     * Create an instance of {@link GeographyValuesType }
     * 
     */
    public GeographyValuesType createGeographyValuesType() {
        return new GeographyValuesType();
    }

    /**
     * Create an instance of {@link TextDomainType }
     * 
     */
    public TextDomainType createTextDomainType() {
        return new TextDomainType();
    }

    /**
     * Create an instance of {@link HistoricalDateType }
     * 
     */
    public HistoricalDateType createHistoricalDateType() {
        return new HistoricalDateType();
    }

    /**
     * Create an instance of {@link LineParameterType }
     * 
     */
    public LineParameterType createLineParameterType() {
        return new LineParameterType();
    }

    /**
     * Create an instance of {@link ImageAreaType }
     * 
     */
    public ImageAreaType createImageAreaType() {
        return new ImageAreaType();
    }

    /**
     * Create an instance of {@link LifecycleInformationType }
     * 
     */
    public LifecycleInformationType createLifecycleInformationType() {
        return new LifecycleInformationType();
    }

    /**
     * Create an instance of {@link GeographyCodeType }
     * 
     */
    public GeographyCodeType createGeographyCodeType() {
        return new GeographyCodeType();
    }

    /**
     * Create an instance of {@link ExcludeType }
     * 
     */
    public ExcludeType createExcludeType() {
        return new ExcludeType();
    }

    /**
     * Create an instance of {@link CoordinatePairsType }
     * 
     */
    public CoordinatePairsType createCoordinatePairsType() {
        return new CoordinatePairsType();
    }

    /**
     * Create an instance of {@link TypedStringType }
     * 
     */
    public TypedStringType createTypedStringType() {
        return new TypedStringType();
    }

    /**
     * Create an instance of {@link URNType }
     * 
     */
    public URNType createURNType() {
        return new URNType();
    }

    /**
     * Create an instance of {@link UserIDType }
     * 
     */
    public UserIDType createUserIDType() {
        return new UserIDType();
    }

    /**
     * Create an instance of {@link CharacterParameterType }
     * 
     */
    public CharacterParameterType createCharacterParameterType() {
        return new CharacterParameterType();
    }

    /**
     * Create an instance of {@link ProgrammingLanguageCodeType }
     * 
     */
    public ProgrammingLanguageCodeType createProgrammingLanguageCodeType() {
        return new ProgrammingLanguageCodeType();
    }

    /**
     * Create an instance of {@link ImageType }
     * 
     */
    public ImageType createImageType() {
        return new ImageType();
    }

    /**
     * Create an instance of {@link SegmentType }
     * 
     */
    public SegmentType createSegmentType() {
        return new SegmentType();
    }

    /**
     * Create an instance of {@link InternationalCodeValueType }
     * 
     */
    public InternationalCodeValueType createInternationalCodeValueType() {
        return new InternationalCodeValueType();
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
        return new NoteType();
    }

    /**
     * Create an instance of {@link SeriesStatementType }
     * 
     */
    public SeriesStatementType createSeriesStatementType() {
        return new SeriesStatementType();
    }

    /**
     * Create an instance of {@link TextualType }
     * 
     */
    public TextualType createTextualType() {
        return new TextualType();
    }

    /**
     * Create an instance of {@link LevelReferenceType }
     * 
     */
    public LevelReferenceType createLevelReferenceType() {
        return new LevelReferenceType();
    }

    /**
     * Create an instance of {@link ProprietaryPropertyType }
     * 
     */
    public ProprietaryPropertyType createProprietaryPropertyType() {
        return new ProprietaryPropertyType();
    }

    /**
     * Create an instance of {@link CommandFileType }
     * 
     */
    public CommandFileType createCommandFileType() {
        return new CommandFileType();
    }

    /**
     * Create an instance of {@link LabelType }
     * 
     */
    public LabelType createLabelType() {
        return new LabelType();
    }

    /**
     * Create an instance of {@link AudioType }
     * 
     */
    public AudioType createAudioType() {
        return new AudioType();
    }

    /**
     * Create an instance of {@link NumberRangeValueType }
     * 
     */
    public NumberRangeValueType createNumberRangeValueType() {
        return new NumberRangeValueType();
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link GeographyValueType }
     * 
     */
    public GeographyValueType createGeographyValueType() {
        return new GeographyValueType();
    }

    /**
     * Create an instance of {@link IDType }
     * 
     */
    public IDType createIDType() {
        return new IDType();
    }

    /**
     * Create an instance of {@link EmptyType }
     * 
     */
    public EmptyType createEmptyType() {
        return new EmptyType();
    }

    /**
     * Create an instance of {@link GeographicStructureType }
     * 
     */
    public GeographicStructureType createGeographicStructureType() {
        return new GeographicStructureType();
    }

    /**
     * Create an instance of {@link VersionType }
     * 
     */
    public VersionType createVersionType() {
        return new VersionType();
    }

    /**
     * Create an instance of {@link EmbargoType }
     * 
     */
    public EmbargoType createEmbargoType() {
        return new EmbargoType();
    }

    /**
     * Create an instance of {@link ProprietaryInfoType }
     * 
     */
    public ProprietaryInfoType createProprietaryInfoType() {
        return new ProprietaryInfoType();
    }

    /**
     * Create an instance of {@link GeographicCoverageType }
     * 
     */
    public GeographicCoverageType createGeographicCoverageType() {
        return new GeographicCoverageType();
    }

    /**
     * Create an instance of {@link FundingInformationType }
     * 
     */
    public FundingInformationType createFundingInformationType() {
        return new FundingInformationType();
    }

    /**
     * Create an instance of {@link TopicalCoverageType }
     * 
     */
    public TopicalCoverageType createTopicalCoverageType() {
        return new TopicalCoverageType();
    }

    /**
     * Create an instance of {@link RangeValueType }
     * 
     */
    public RangeValueType createRangeValueType() {
        return new RangeValueType();
    }

    /**
     * Create an instance of {@link BoundingBoxType }
     * 
     */
    public BoundingBoxType createBoundingBoxType() {
        return new BoundingBoxType();
    }

    /**
     * Create an instance of {@link ParentGeographyType }
     * 
     */
    public ParentGeographyType createParentGeographyType() {
        return new ParentGeographyType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     * 
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link VideoType }
     * 
     */
    public VideoType createVideoType() {
        return new VideoType();
    }

    /**
     * Create an instance of {@link CommandType }
     * 
     */
    public CommandType createCommandType() {
        return new CommandType();
    }

    /**
     * Create an instance of {@link GeographicLocationType }
     * 
     */
    public GeographicLocationType createGeographicLocationType() {
        return new GeographicLocationType();
    }

    /**
     * Create an instance of {@link PolygonType }
     * 
     */
    public PolygonType createPolygonType() {
        return new PolygonType();
    }

    /**
     * Create an instance of {@link NumberRangeType }
     * 
     */
    public NumberRangeType createNumberRangeType() {
        return new NumberRangeType();
    }

    /**
     * Create an instance of {@link GeographyType }
     * 
     */
    public GeographyType createGeographyType() {
        return new GeographyType();
    }

    /**
     * Create an instance of {@link OtherMaterialType }
     * 
     */
    public OtherMaterialType createOtherMaterialType() {
        return new OtherMaterialType();
    }

    /**
     * Create an instance of {@link CreatorType }
     * 
     */
    public CreatorType createCreatorType() {
        return new CreatorType();
    }

    /**
     * Create an instance of {@link CitationType }
     * 
     */
    public CitationType createCitationType() {
        return new CitationType();
    }

    /**
     * Create an instance of {@link ContributorType }
     * 
     */
    public ContributorType createContributorType() {
        return new ContributorType();
    }

    /**
     * Create an instance of {@link GeographicLevelType }
     * 
     */
    public GeographicLevelType createGeographicLevelType() {
        return new GeographicLevelType();
    }

    /**
     * Create an instance of {@link LifecycleEventType }
     * 
     */
    public LifecycleEventType createLifecycleEventType() {
        return new LifecycleEventType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link DateTimeRepresentationType }
     * 
     */
    public DateTimeRepresentationType createDateTimeRepresentationType() {
        return new DateTimeRepresentationType();
    }

    /**
     * Create an instance of {@link GeographicRepresentationType }
     * 
     */
    public GeographicRepresentationType createGeographicRepresentationType() {
        return new GeographicRepresentationType();
    }

    /**
     * Create an instance of {@link TextRepresentationType }
     * 
     */
    public TextRepresentationType createTextRepresentationType() {
        return new TextRepresentationType();
    }

    /**
     * Create an instance of {@link ExternalCategoryRepresentationType }
     * 
     */
    public ExternalCategoryRepresentationType createExternalCategoryRepresentationType() {
        return new ExternalCategoryRepresentationType();
    }

    /**
     * Create an instance of {@link CategoryRepresentationType }
     * 
     */
    public CategoryRepresentationType createCategoryRepresentationType() {
        return new CategoryRepresentationType();
    }

    /**
     * Create an instance of {@link NumericRepresentationType }
     * 
     */
    public NumericRepresentationType createNumericRepresentationType() {
        return new NumericRepresentationType();
    }

    /**
     * Create an instance of {@link CodeRepresentationType }
     * 
     */
    public CodeRepresentationType createCodeRepresentationType() {
        return new CodeRepresentationType();
    }

    /**
     * Create an instance of {@link IdentifiedStructuredStringType }
     * 
     */
    public IdentifiedStructuredStringType createIdentifiedStructuredStringType() {
        return new IdentifiedStructuredStringType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographyCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographyCode")
    public JAXBElement<GeographyCodeType> createGeographyCode(GeographyCodeType value) {
        return new JAXBElement<GeographyCodeType>(_GeographyCode_QNAME, GeographyCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SouthLatitude")
    public JAXBElement<BigDecimal> createSouthLatitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_SouthLatitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "AuthorityOrganizationReference")
    public JAXBElement<ReferenceType> createAuthorityOrganizationReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_AuthorityOrganizationReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistoricalDateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "HistoricalDate")
    public JAXBElement<HistoricalDateType> createHistoricalDate(HistoricalDateType value) {
        return new JAXBElement<HistoricalDateType>(_HistoricalDate_QNAME, HistoricalDateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextDomainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "AlternateObject")
    public JAXBElement<TextDomainType> createAlternateObject(TextDomainType value) {
        return new JAXBElement<TextDomainType>(_AlternateObject_QNAME, TextDomainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "ImageArea")
    public JAXBElement<ImageAreaType> createImageArea(ImageAreaType value) {
        return new JAXBElement<ImageAreaType>(_ImageArea_QNAME, ImageAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "LineParameter")
    public JAXBElement<LineParameterType> createLineParameter(LineParameterType value) {
        return new JAXBElement<LineParameterType>(_LineParameter_QNAME, LineParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Date")
    public JAXBElement<DateType> createDate(DateType value) {
        return new JAXBElement<DateType>(_Date_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "StartDate")
    public JAXBElement<String> createStartDate(String value) {
        return new JAXBElement<String>(_StartDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemporalCoverageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "TemporalCoverage")
    public JAXBElement<TemporalCoverageType> createTemporalCoverage(TemporalCoverageType value) {
        return new JAXBElement<TemporalCoverageType>(_TemporalCoverage_QNAME, TemporalCoverageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpatialCoordinateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "YCoordinate")
    public JAXBElement<SpatialCoordinateType> createYCoordinate(SpatialCoordinateType value) {
        return new JAXBElement<SpatialCoordinateType>(_YCoordinate_QNAME, SpatialCoordinateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "TopicalCoverageReference")
    public JAXBElement<ReferenceType> createTopicalCoverageReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_TopicalCoverageReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SoftwarePackage")
    public JAXBElement<CodeValueType> createSoftwarePackage(CodeValueType value) {
        return new JAXBElement<CodeValueType>(_SoftwarePackage_QNAME, CodeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AudioType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Audio")
    public JAXBElement<AudioType> createAudio(AudioType value) {
        return new JAXBElement<AudioType>(_Audio_QNAME, AudioType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProprietaryPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "ProprietaryProperty")
    public JAXBElement<ProprietaryPropertyType> createProprietaryProperty(ProprietaryPropertyType value) {
        return new JAXBElement<ProprietaryPropertyType>(_ProprietaryProperty_QNAME, ProprietaryPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommandFileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "CommandFile")
    public JAXBElement<CommandFileType> createCommandFile(CommandFileType value) {
        return new JAXBElement<CommandFileType>(_CommandFile_QNAME, CommandFileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Scheme")
    public JAXBElement<ReferenceType> createScheme(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_Scheme_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Copyright")
    public JAXBElement<InternationalStringType> createCopyright(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_Copyright_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link URNType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "URN")
    public JAXBElement<URNType> createURN(URNType value) {
        return new JAXBElement<URNType>(_URN_QNAME, URNType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "DefaultDecimalSeparator")
    public JAXBElement<String> createDefaultDecimalSeparator(String value) {
        return new JAXBElement<String>(_DefaultDecimalSeparator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "EastLongitude")
    public JAXBElement<BigDecimal> createEastLongitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_EastLongitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographyValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographyValue")
    public JAXBElement<GeographyValueType> createGeographyValue(GeographyValueType value) {
        return new JAXBElement<GeographyValueType>(_GeographyValue_QNAME, GeographyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Name")
    public JAXBElement<InternationalStringType> createName(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_Name_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LifecycleEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "LifecycleEvent")
    public JAXBElement<LifecycleEventType> createLifecycleEvent(LifecycleEventType value) {
        return new JAXBElement<LifecycleEventType>(_LifecycleEvent_QNAME, LifecycleEventType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "AlternateTitle")
    public JAXBElement<InternationalStringType> createAlternateTitle(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_AlternateTitle_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "EnforcementAgencyOrganizationReference")
    public JAXBElement<ReferenceType> createEnforcementAgencyOrganizationReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_EnforcementAgencyOrganizationReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchemeReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SchemeReference")
    public JAXBElement<SchemeReferenceType> createSchemeReference(SchemeReferenceType value) {
        return new JAXBElement<SchemeReferenceType>(_SchemeReference_QNAME, SchemeReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographyStructureVariable")
    public JAXBElement<ReferenceType> createGeographyStructureVariable(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_GeographyStructureVariable_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NumberRangeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Low")
    public JAXBElement<NumberRangeValueType> createLow(NumberRangeValueType value) {
        return new JAXBElement<NumberRangeValueType>(_Low_QNAME, NumberRangeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographicLocation")
    public JAXBElement<GeographicLocationType> createGeographicLocation(GeographicLocationType value) {
        return new JAXBElement<GeographicLocationType>(_GeographicLocation_QNAME, GeographicLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpatialCoordinateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "XCoordinate")
    public JAXBElement<SpatialCoordinateType> createXCoordinate(SpatialCoordinateType value) {
        return new JAXBElement<SpatialCoordinateType>(_XCoordinate_QNAME, SpatialCoordinateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VideoClipTypeCodedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "VideoClipType")
    public JAXBElement<VideoClipTypeCodedType> createVideoClipType(VideoClipTypeCodedType value) {
        return new JAXBElement<VideoClipTypeCodedType>(_VideoClipType_QNAME, VideoClipTypeCodedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographicTime")
    public JAXBElement<DateType> createGeographicTime(DateType value) {
        return new JAXBElement<DateType>(_GeographicTime_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographicLevelReference")
    public JAXBElement<ReferenceType> createGeographicLevelReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_GeographicLevelReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "InternationalIdentifier")
    public JAXBElement<TypedStringType> createInternationalIdentifier(TypedStringType value) {
        return new JAXBElement<TypedStringType>(_InternationalIdentifier_QNAME, TypedStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographyValuesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Values")
    public JAXBElement<GeographyValuesType> createValues(GeographyValuesType value) {
        return new JAXBElement<GeographyValuesType>(_Values_QNAME, GeographyValuesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LifecycleInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "LifecycleInformation")
    public JAXBElement<LifecycleInformationType> createLifecycleInformation(LifecycleInformationType value) {
        return new JAXBElement<LifecycleInformationType>(_LifecycleInformation_QNAME, LifecycleInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographicStructureReference")
    public JAXBElement<ReferenceType> createGeographicStructureReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_GeographicStructureReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SeriesName")
    public JAXBElement<NameType> createSeriesName(NameType value) {
        return new JAXBElement<NameType>(_SeriesName_QNAME, NameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NumberRangeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "High")
    public JAXBElement<NumberRangeValueType> createHigh(NumberRangeValueType value) {
        return new JAXBElement<NumberRangeValueType>(_High_QNAME, NumberRangeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SourceQuestionReference")
    public JAXBElement<ReferenceType> createSourceQuestionReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_SourceQuestionReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographicLevelDescription")
    public JAXBElement<StructuredStringType> createGeographicLevelDescription(StructuredStringType value) {
        return new JAXBElement<StructuredStringType>(_GeographicLevelDescription_QNAME, StructuredStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LabelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Label")
    public JAXBElement<LabelType> createLabel(LabelType value) {
        return new JAXBElement<LabelType>(_Label_QNAME, LabelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalCodeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Subject")
    public JAXBElement<InternationalCodeValueType> createSubject(InternationalCodeValueType value) {
        return new JAXBElement<InternationalCodeValueType>(_Subject_QNAME, InternationalCodeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "RelationshipDescription")
    public JAXBElement<InternationalStringType> createRelationshipDescription(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_RelationshipDescription_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Title")
    public JAXBElement<InternationalStringType> createTitle(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_Title_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Note")
    public JAXBElement<NoteType> createNote(NoteType value) {
        return new JAXBElement<NoteType>(_Note_QNAME, NoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Image")
    public JAXBElement<ImageType> createImage(ImageType value) {
        return new JAXBElement<ImageType>(_Image_QNAME, ImageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicDescriptionCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SpatialObject")
    public JAXBElement<GeographicDescriptionCodeType> createSpatialObject(GeographicDescriptionCodeType value) {
        return new JAXBElement<GeographicDescriptionCodeType>(_SpatialObject_QNAME, GeographicDescriptionCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgrammingLanguageCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Code")
    public JAXBElement<ProgrammingLanguageCodeType> createCode(ProgrammingLanguageCodeType value) {
        return new JAXBElement<ProgrammingLanguageCodeType>(_Code_QNAME, ProgrammingLanguageCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "UserID")
    public JAXBElement<UserIDType> createUserID(UserIDType value) {
        return new JAXBElement<UserIDType>(_UserID_QNAME, UserIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParentGeographyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "ParentGeography")
    public JAXBElement<ParentGeographyType> createParentGeography(ParentGeographyType value) {
        return new JAXBElement<ParentGeographyType>(_ParentGeography_QNAME, ParentGeographyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "RelationshipDescripton")
    public JAXBElement<InternationalStringType> createRelationshipDescripton(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_RelationshipDescripton_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "EndDate")
    public JAXBElement<String> createEndDate(String value) {
        return new JAXBElement<String>(_EndDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RangeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "MaximumValue")
    public JAXBElement<RangeValueType> createMaximumValue(RangeValueType value) {
        return new JAXBElement<RangeValueType>(_MaximumValue_QNAME, RangeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographyName")
    public JAXBElement<InternationalStringType> createGeographyName(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_GeographyName_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistoricalDateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "HistoricalStartDate")
    public JAXBElement<HistoricalDateType> createHistoricalStartDate(HistoricalDateType value) {
        return new JAXBElement<HistoricalDateType>(_HistoricalStartDate_QNAME, HistoricalDateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VideoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Video")
    public JAXBElement<VideoType> createVideo(VideoType value) {
        return new JAXBElement<VideoType>(_Video_QNAME, VideoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "AnalysisUnit")
    public JAXBElement<CodeValueType> createAnalysisUnit(CodeValueType value) {
        return new JAXBElement<CodeValueType>(_AnalysisUnit_QNAME, CodeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SubTitle")
    public JAXBElement<InternationalStringType> createSubTitle(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_SubTitle_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingInformationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "FundingInformation")
    public JAXBElement<FundingInformationType> createFundingInformation(FundingInformationType value) {
        return new JAXBElement<FundingInformationType>(_FundingInformation_QNAME, FundingInformationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Version")
    public JAXBElement<VersionType> createVersion(VersionType value) {
        return new JAXBElement<VersionType>(_Version_QNAME, VersionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmptyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Add")
    public JAXBElement<EmptyType> createAdd(EmptyType value) {
        return new JAXBElement<EmptyType>(_Add_QNAME, EmptyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShapeCodedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Shape")
    public JAXBElement<ShapeCodedType> createShape(ShapeCodedType value) {
        return new JAXBElement<ShapeCodedType>(_Shape_QNAME, ShapeCodedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolygonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "BoundingPolygon")
    public JAXBElement<PolygonType> createBoundingPolygon(PolygonType value) {
        return new JAXBElement<PolygonType>(_BoundingPolygon_QNAME, PolygonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextDomainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "AlternateCoordinateSystem")
    public JAXBElement<TextDomainType> createAlternateCoordinateSystem(TextDomainType value) {
        return new JAXBElement<TextDomainType>(_AlternateCoordinateSystem_QNAME, TextDomainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "CategorySchemeReference")
    public JAXBElement<ReferenceType> createCategorySchemeReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_CategorySchemeReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "RelatedToReference")
    public JAXBElement<ReferenceType> createRelatedToReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_RelatedToReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Description")
    public JAXBElement<StructuredStringType> createDescription(StructuredStringType value) {
        return new JAXBElement<StructuredStringType>(_Description_QNAME, StructuredStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CitationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Citation")
    public JAXBElement<CitationType> createCitation(CitationType value) {
        return new JAXBElement<CitationType>(_Citation_QNAME, CitationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolygonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "ExcludingPolygon")
    public JAXBElement<PolygonType> createExcludingPolygon(PolygonType value) {
        return new JAXBElement<PolygonType>(_ExcludingPolygon_QNAME, PolygonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Rationale")
    public JAXBElement<StructuredStringType> createRationale(StructuredStringType value) {
        return new JAXBElement<StructuredStringType>(_Rationale_QNAME, StructuredStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Geography")
    public JAXBElement<GeographyType> createGeography(GeographyType value) {
        return new JAXBElement<GeographyType>(_Geography_QNAME, GeographyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AudioClipTypeCodedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "AudioClipType")
    public JAXBElement<AudioClipTypeCodedType> createAudioClipType(AudioClipTypeCodedType value) {
        return new JAXBElement<AudioClipTypeCodedType>(_AudioClipType_QNAME, AudioClipTypeCodedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Publisher")
    public JAXBElement<InternationalStringType> createPublisher(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_Publisher_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SeriesDescription")
    public JAXBElement<StructuredStringType> createSeriesDescription(StructuredStringType value) {
        return new JAXBElement<StructuredStringType>(_SeriesDescription_QNAME, StructuredStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "TopCode")
    public JAXBElement<BigDecimal> createTopCode(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TopCode_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoverageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Coverage")
    public JAXBElement<CoverageType> createCoverage(CoverageType value) {
        return new JAXBElement<CoverageType>(_Coverage_QNAME, CoverageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "CoverageLimitation")
    public JAXBElement<InternationalStringType> createCoverageLimitation(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_CoverageLimitation_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Module")
    public JAXBElement<ReferenceType> createModule(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_Module_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SegmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Segment")
    public JAXBElement<SegmentType> createSegment(SegmentType value) {
        return new JAXBElement<SegmentType>(_Segment_QNAME, SegmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextDomainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "AlternateOffset")
    public JAXBElement<TextDomainType> createAlternateOffset(TextDomainType value) {
        return new JAXBElement<TextDomainType>(_AlternateOffset_QNAME, TextDomainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SummaryDataReference")
    public JAXBElement<ReferenceType> createSummaryDataReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_SummaryDataReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographyReference")
    public JAXBElement<ReferenceType> createGeographyReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_GeographyReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CharacterParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "CharacterParameter")
    public JAXBElement<CharacterParameterType> createCharacterParameter(CharacterParameterType value) {
        return new JAXBElement<CharacterParameterType>(_CharacterParameter_QNAME, CharacterParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BoundingBoxType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "BoundingBox")
    public JAXBElement<BoundingBoxType> createBoundingBox(BoundingBoxType value) {
        return new JAXBElement<BoundingBoxType>(_BoundingBox_QNAME, BoundingBoxType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationshipType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Relationship")
    public JAXBElement<RelationshipType> createRelationship(RelationshipType value) {
        return new JAXBElement<RelationshipType>(_Relationship_QNAME, RelationshipType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProprietaryInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "ProprietaryInfo")
    public JAXBElement<ProprietaryInfoType> createProprietaryInfo(ProprietaryInfoType value) {
        return new JAXBElement<ProprietaryInfoType>(_ProprietaryInfo_QNAME, ProprietaryInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicCoverageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SpatialCoverage")
    public JAXBElement<GeographicCoverageType> createSpatialCoverage(GeographicCoverageType value) {
        return new JAXBElement<GeographicCoverageType>(_SpatialCoverage_QNAME, GeographicCoverageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmbargoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Embargo")
    public JAXBElement<EmbargoType> createEmbargo(EmbargoType value) {
        return new JAXBElement<EmbargoType>(_Embargo_QNAME, EmbargoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "VersionRationale")
    public JAXBElement<InternationalStringType> createVersionRationale(InternationalStringType value) {
        return new JAXBElement<InternationalStringType>(_VersionRationale_QNAME, InternationalStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "ID")
    public JAXBElement<IDType> createID(IDType value) {
        return new JAXBElement<IDType>(_ID_QNAME, IDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Delete")
    public JAXBElement<ReferenceType> createDelete(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_Delete_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "TemporalCoverageReference")
    public JAXBElement<ReferenceType> createTemporalCoverageReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_TemporalCoverageReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "DefaultDigitGroupSeparator")
    public JAXBElement<String> createDefaultDigitGroupSeparator(String value) {
        return new JAXBElement<String>(_DefaultDigitGroupSeparator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "AgencyOrganizationReference")
    public JAXBElement<ReferenceType> createAgencyOrganizationReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_AgencyOrganizationReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "NorthLatitude")
    public JAXBElement<BigDecimal> createNorthLatitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NorthLatitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Replace")
    public JAXBElement<ReferenceType> createReplace(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_Replace_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicLevelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Level")
    public JAXBElement<GeographicLevelType> createLevel(GeographicLevelType value) {
        return new JAXBElement<GeographicLevelType>(_Level_QNAME, GeographicLevelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographicLocationReference")
    public JAXBElement<ReferenceType> createGeographicLocationReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_GeographicLocationReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Creator")
    public JAXBElement<CreatorType> createCreator(CreatorType value) {
        return new JAXBElement<CreatorType>(_Creator_QNAME, CreatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SpatialCoverageReference")
    public JAXBElement<ReferenceType> createSpatialCoverageReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_SpatialCoverageReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "PublicationDate")
    public JAXBElement<DateType> createPublicationDate(DateType value) {
        return new JAXBElement<DateType>(_PublicationDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RangeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "MinimumValue")
    public JAXBElement<RangeValueType> createMinimumValue(RangeValueType value) {
        return new JAXBElement<RangeValueType>(_MinimumValue_QNAME, RangeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Reason")
    public JAXBElement<StructuredStringType> createReason(StructuredStringType value) {
        return new JAXBElement<StructuredStringType>(_Reason_QNAME, StructuredStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "TimeZone")
    public JAXBElement<String> createTimeZone(String value) {
        return new JAXBElement<String>(_TimeZone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredCommandType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "StructuredCommand")
    public JAXBElement<StructuredCommandType> createStructuredCommand(StructuredCommandType value) {
        return new JAXBElement<StructuredCommandType>(_StructuredCommand_QNAME, StructuredCommandType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographicLayerBase")
    public JAXBElement<ReferenceType> createGeographicLayerBase(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_GeographicLayerBase_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoordinatePairsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "CoordinatePairs")
    public JAXBElement<CoordinatePairsType> createCoordinatePairs(CoordinatePairsType value) {
        return new JAXBElement<CoordinatePairsType>(_CoordinatePairs_QNAME, CoordinatePairsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExcludeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Exclude")
    public JAXBElement<ExcludeType> createExclude(ExcludeType value) {
        return new JAXBElement<ExcludeType>(_Exclude_QNAME, ExcludeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Point")
    public JAXBElement<PointType> createPoint(PointType value) {
        return new JAXBElement<PointType>(_Point_QNAME, PointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "User")
    public JAXBElement<StructuredStringType> createUser(StructuredStringType value) {
        return new JAXBElement<StructuredStringType>(_User_QNAME, StructuredStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LevelReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "TopLevelReference")
    public JAXBElement<LevelReferenceType> createTopLevelReference(LevelReferenceType value) {
        return new JAXBElement<LevelReferenceType>(_TopLevelReference_QNAME, LevelReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextualType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Textual")
    public JAXBElement<TextualType> createTextual(TextualType value) {
        return new JAXBElement<TextualType>(_Textual_QNAME, TextualType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SeriesStatementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SeriesStatement")
    public JAXBElement<SeriesStatementType> createSeriesStatement(SeriesStatementType value) {
        return new JAXBElement<SeriesStatementType>(_SeriesStatement_QNAME, SeriesStatementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuredStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Content")
    public JAXBElement<StructuredStringType> createContent(StructuredStringType value) {
        return new JAXBElement<StructuredStringType>(_Content_QNAME, StructuredStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "CodeSchemeReference")
    public JAXBElement<ReferenceType> createCodeSchemeReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_CodeSchemeReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "VersionDate")
    public JAXBElement<DateType> createVersionDate(DateType value) {
        return new JAXBElement<DateType>(_VersionDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "LevelReference")
    public JAXBElement<ReferenceType> createLevelReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_LevelReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "VariableReference")
    public JAXBElement<ReferenceType> createVariableReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_VariableReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "SimpleDate")
    public JAXBElement<String> createSimpleDate(String value) {
        return new JAXBElement<String>(_SimpleDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "WestLongitude")
    public JAXBElement<BigDecimal> createWestLongitude(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_WestLongitude_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TopicalCoverageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "TopicalCoverage")
    public JAXBElement<TopicalCoverageType> createTopicalCoverage(TopicalCoverageType value) {
        return new JAXBElement<TopicalCoverageType>(_TopicalCoverage_QNAME, TopicalCoverageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "UniverseReference")
    public JAXBElement<ReferenceType> createUniverseReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_UniverseReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "EventType")
    public JAXBElement<CodeValueType> createEventType(CodeValueType value) {
        return new JAXBElement<CodeValueType>(_EventType_QNAME, CodeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LevelReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "LowestLevelReference")
    public JAXBElement<LevelReferenceType> createLowestLevelReference(LevelReferenceType value) {
        return new JAXBElement<LevelReferenceType>(_LowestLevelReference_QNAME, LevelReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicStructureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "GeographicStructure")
    public JAXBElement<GeographicStructureType> createGeographicStructure(GeographicStructureType value) {
        return new JAXBElement<GeographicStructureType>(_GeographicStructure_QNAME, GeographicStructureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoftwareType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Software")
    public JAXBElement<SoftwareType> createSoftware(SoftwareType value) {
        return new JAXBElement<SoftwareType>(_Software_QNAME, SoftwareType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "ReferenceDate")
    public JAXBElement<DateType> createReferenceDate(DateType value) {
        return new JAXBElement<DateType>(_ReferenceDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContributorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Contributor")
    public JAXBElement<ContributorType> createContributor(ContributorType value) {
        return new JAXBElement<ContributorType>(_Contributor_QNAME, ContributorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherMaterialType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "OtherMaterial")
    public JAXBElement<OtherMaterialType> createOtherMaterial(OtherMaterialType value) {
        return new JAXBElement<OtherMaterialType>(_OtherMaterial_QNAME, OtherMaterialType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "EmbargoName")
    public JAXBElement<NameType> createEmbargoName(NameType value) {
        return new JAXBElement<NameType>(_EmbargoName_QNAME, NameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistoricalDateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "HistoricalEndDate")
    public JAXBElement<HistoricalDateType> createHistoricalEndDate(HistoricalDateType value) {
        return new JAXBElement<HistoricalDateType>(_HistoricalEndDate_QNAME, HistoricalDateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NumberRangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "NumberRange")
    public JAXBElement<NumberRangeType> createNumberRange(NumberRangeType value) {
        return new JAXBElement<NumberRangeType>(_NumberRange_QNAME, NumberRangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommandType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Command")
    public JAXBElement<CommandType> createCommand(CommandType value) {
        return new JAXBElement<CommandType>(_Command_QNAME, CommandType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InternationalCodeValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "Keyword")
    public JAXBElement<InternationalCodeValueType> createKeyword(InternationalCodeValueType value) {
        return new JAXBElement<InternationalCodeValueType>(_Keyword_QNAME, InternationalCodeValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "ddi:reusable:3_1", name = "IdentifyingAgency", scope = ReferenceType.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReferenceTypeIdentifyingAgency(String value) {
        return new JAXBElement<String>(_ReferenceTypeIdentifyingAgency_QNAME, String.class, ReferenceType.class, value);
    }

}
