//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.reusable._3_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A geographic point consisting of an X and Y coordinate.
 * 
 * <p>Java class for PointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:reusable:3_1}XCoordinate"/>
 *         &lt;element ref="{ddi:reusable:3_1}YCoordinate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointType", propOrder = {
    "xCoordinate",
    "yCoordinate"
})
public class PointType {

    @XmlElement(name = "XCoordinate", required = true)
    protected SpatialCoordinateType xCoordinate;
    @XmlElement(name = "YCoordinate", required = true)
    protected SpatialCoordinateType yCoordinate;

    /**
     * An X coordinate (latitudinal equivalent) value.
     * 
     * @return
     *     possible object is
     *     {@link SpatialCoordinateType }
     *     
     */
    public SpatialCoordinateType getXCoordinate() {
        return xCoordinate;
    }

    /**
     * Sets the value of the xCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpatialCoordinateType }
     *     
     */
    public void setXCoordinate(SpatialCoordinateType value) {
        this.xCoordinate = value;
    }

    /**
     * A Y coordinate (longitudinal equivalent) value.
     * 
     * @return
     *     possible object is
     *     {@link SpatialCoordinateType }
     *     
     */
    public SpatialCoordinateType getYCoordinate() {
        return yCoordinate;
    }

    /**
     * Sets the value of the yCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpatialCoordinateType }
     *     
     */
    public void setYCoordinate(SpatialCoordinateType value) {
        this.yCoordinate = value;
    }

}
