//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.reusable._3_1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains information proprietary to the software package which produced the data file. This is expressed as a set of name-value pairs. 
 * 
 * <p>Java class for ProprietaryInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProprietaryInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:reusable:3_1}ProprietaryProperty" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProprietaryInfoType", propOrder = {
    "proprietaryProperty"
})
public class ProprietaryInfoType {

    @XmlElement(name = "ProprietaryProperty", required = true)
    protected List<ProprietaryPropertyType> proprietaryProperty;

    /**
     * Gets the value of the proprietaryProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the proprietaryProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProprietaryProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProprietaryPropertyType }
     * 
     * 
     */
    public List<ProprietaryPropertyType> getProprietaryProperty() {
        if (proprietaryProperty == null) {
            proprietaryProperty = new ArrayList<ProprietaryPropertyType>();
        }
        return this.proprietaryProperty;
    }

}
