//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.physicaldataproduct._3_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ddi.reusable._3_1.ReferenceType;


/**
 * Includes a reference to a variable, and information about its data item location and its data type/format.
 * 
 * <p>Java class for DataItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{ddi:physicaldataproduct:3_1}VariableReference"/>
 *         &lt;element ref="{ddi:physicaldataproduct:3_1}PhysicalLocation"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataItemType", propOrder = {
    "variableReference",
    "physicalLocation"
})
public class DataItemType {

    @XmlElement(name = "VariableReference", required = true)
    protected ReferenceType variableReference;
    @XmlElement(name = "PhysicalLocation", required = true)
    protected PhysicalLocationType physicalLocation;

    /**
     * Reference to the variable expressed in this data item.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getVariableReference() {
        return variableReference;
    }

    /**
     * Sets the value of the variableReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setVariableReference(ReferenceType value) {
        this.variableReference = value;
    }

    /**
     * Includes information about the relevant record group, as well as the data item location and data type/format information for the referenced variable.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalLocationType }
     *     
     */
    public PhysicalLocationType getPhysicalLocation() {
        return physicalLocation;
    }

    /**
     * Sets the value of the physicalLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalLocationType }
     *     
     */
    public void setPhysicalLocation(PhysicalLocationType value) {
        this.physicalLocation = value;
    }

}
