//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.22 at 02:00:24 PM CEST 
//


package ddi.datacollection._3_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ddi.reusable._3_1.CodeValueType;
import ddi.reusable._3_1.DateType;


/**
 * Documents the intended frequency of data collection, for example monthly, yearly, weekly, etc.,  preferably using an optional controlled vocabulary in the IntendedFrequency element. Date of first collection should be provided in StartDate as a basis for defining periodicity. EndDate should be entered for data collection cycles with a known or anticipated end date. EndDate is omitted in data collection series that are intended to be on-going.
 * 
 * <p>Java class for DataCollectionFrequencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataCollectionFrequencyType">
 *   &lt;complexContent>
 *     &lt;extension base="{ddi:reusable:3_1}DateType">
 *       &lt;sequence>
 *         &lt;element name="IntendedFrequency" type="{ddi:reusable:3_1}CodeValueType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataCollectionFrequencyType", propOrder = {
    "intendedFrequency"
})
public class DataCollectionFrequencyType
    extends DateType
{

    @XmlElement(name = "IntendedFrequency")
    protected CodeValueType intendedFrequency;

    /**
     * Gets the value of the intendedFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link CodeValueType }
     *     
     */
    public CodeValueType getIntendedFrequency() {
        return intendedFrequency;
    }

    /**
     * Sets the value of the intendedFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeValueType }
     *     
     */
    public void setIntendedFrequency(CodeValueType value) {
        this.intendedFrequency = value;
    }

}
